# Generated by Django 4.2.7 on 2025-07-29 18:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('image', 'Image'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'mp4', 'avi', 'mov', 'mp3', 'wav', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'zip', 'rar'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('is_public', models.BooleanField(default=False, help_text='Available to all enrolled students')),
                ('is_downloadable', models.BooleanField(default=True, help_text='Students can download this material')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
            ],
            options={
                'verbose_name': 'Material Access',
                'verbose_name_plural': 'Material Accesses',
                'db_table': 'material_accesses',
            },
        ),
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_folders', to='courses.course')),
            ],
            options={
                'verbose_name': 'Material Folder',
                'verbose_name_plural': 'Material Folders',
                'db_table': 'material_folders',
            },
        ),
    ]
