# Generated by Django 4.2.7 on 2025-07-29 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('live_classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassparticipant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveclassparticipant',
            name='live_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live_classes.liveclass'),
        ),
        migrations.AddField(
            model_name='liveclassparticipant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveclassmessage',
            name='live_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live_classes.liveclass'),
        ),
        migrations.AddField(
            model_name='liveclassmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='live_classes.liveclassmessage'),
        ),
        migrations.AddField(
            model_name='liveclassmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='liveclassparticipant',
            unique_together={('student', 'live_class')},
        ),
    ]
